/*
 * This file is generated by jOOQ.
*/
package com.csc625.checkin.database.tables.records;


import com.csc625.checkin.database.tables.Qrcode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrcodeRecord extends UpdatableRecordImpl<QrcodeRecord> implements Record4<Integer, Integer, String, byte[]> {

    private static final long serialVersionUID = -2085167191;

    /**
     * Setter for <code>checkin.qrcode.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>checkin.qrcode.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>checkin.qrcode.Student_ID</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>checkin.qrcode.Student_ID</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>checkin.qrcode.Active</code>.
     */
    public void setActive(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>checkin.qrcode.Active</code>.
     */
    public String getActive() {
        return (String) get(2);
    }

    /**
     * Setter for <code>checkin.qrcode.Code</code>.
     */
    public void setCode(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>checkin.qrcode.Code</code>.
     */
    public byte[] getCode() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Qrcode.QRCODE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Qrcode.QRCODE.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Qrcode.QRCODE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return Qrcode.QRCODE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrcodeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrcodeRecord value2(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrcodeRecord value3(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrcodeRecord value4(byte... value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrcodeRecord values(Integer value1, Integer value2, String value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QrcodeRecord
     */
    public QrcodeRecord() {
        super(Qrcode.QRCODE);
    }

    /**
     * Create a detached, initialised QrcodeRecord
     */
    public QrcodeRecord(Integer id, Integer studentId, String active, byte[] code) {
        super(Qrcode.QRCODE);

        set(0, id);
        set(1, studentId);
        set(2, active);
        set(3, code);
    }
}
