/*
 * This file is generated by jOOQ.
*/
package com.csc625.checkin.database.tables.records;


import com.csc625.checkin.database.tables.User;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record7<Integer, String, String, Date, String, String, String> {

    private static final long serialVersionUID = -1006924651;

    /**
     * Setter for <code>checkin.user.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>checkin.user.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>checkin.user.Email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>checkin.user.Email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>checkin.user.UID</code>.
     */
    public void setUid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>checkin.user.UID</code>.
     */
    public String getUid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>checkin.user.Last_Login</code>.
     */
    public void setLastLogin(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>checkin.user.Last_Login</code>.
     */
    public Date getLastLogin() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>checkin.user.Active</code>.
     */
    public void setActive(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>checkin.user.Active</code>.
     */
    public String getActive() {
        return (String) get(4);
    }

    /**
     * Setter for <code>checkin.user.FirstName</code>.
     */
    public void setFirstname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>checkin.user.FirstName</code>.
     */
    public String getFirstname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>checkin.user.LastName</code>.
     */
    public void setLastname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>checkin.user.LastName</code>.
     */
    public String getLastname() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Date, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Date, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return User.USER.LAST_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return User.USER.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(Date value) {
        setLastLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, String value3, Date value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String email, String uid, Date lastLogin, String active, String firstname, String lastname) {
        super(User.USER);

        set(0, id);
        set(1, email);
        set(2, uid);
        set(3, lastLogin);
        set(4, active);
        set(5, firstname);
        set(6, lastname);
    }
}
