/*
 * This file is generated by jOOQ.
*/
package com.csc625.checkin.database;


import com.csc625.checkin.database.tables.Checkins;
import com.csc625.checkin.database.tables.Qrcode;
import com.csc625.checkin.database.tables.Student;
import com.csc625.checkin.database.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Checkin extends SchemaImpl {

    private static final long serialVersionUID = 465865462;

    /**
     * The reference instance of <code>checkin</code>
     */
    public static final Checkin CHECKIN = new Checkin();

    /**
     * The table <code>checkin.checkins</code>.
     */
    public final Checkins CHECKINS = com.csc625.checkin.database.tables.Checkins.CHECKINS;

    /**
     * The table <code>checkin.qrcode</code>.
     */
    public final Qrcode QRCODE = com.csc625.checkin.database.tables.Qrcode.QRCODE;

    /**
     * The table <code>checkin.student</code>.
     */
    public final Student STUDENT = com.csc625.checkin.database.tables.Student.STUDENT;

    /**
     * The table <code>checkin.user</code>.
     */
    public final User USER = com.csc625.checkin.database.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Checkin() {
        super("checkin", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Checkins.CHECKINS,
            Qrcode.QRCODE,
            Student.STUDENT,
            User.USER);
    }
}
