/*
 * This file is generated by jOOQ.
*/
package com.csc625.checkin.database;


import com.csc625.checkin.database.tables.Checkins;
import com.csc625.checkin.database.tables.Qrcode;
import com.csc625.checkin.database.tables.Student;
import com.csc625.checkin.database.tables.User;
import com.csc625.checkin.database.tables.records.CheckinsRecord;
import com.csc625.checkin.database.tables.records.QrcodeRecord;
import com.csc625.checkin.database.tables.records.StudentRecord;
import com.csc625.checkin.database.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>checkin</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CheckinsRecord, Integer> IDENTITY_CHECKINS = Identities0.IDENTITY_CHECKINS;
    public static final Identity<QrcodeRecord, Integer> IDENTITY_QRCODE = Identities0.IDENTITY_QRCODE;
    public static final Identity<StudentRecord, Integer> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CheckinsRecord> KEY_CHECKINS_PRIMARY = UniqueKeys0.KEY_CHECKINS_PRIMARY;
    public static final UniqueKey<QrcodeRecord> KEY_QRCODE_PRIMARY = UniqueKeys0.KEY_QRCODE_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CheckinsRecord, StudentRecord> CHECKINS_IDFK_1 = ForeignKeys0.CHECKINS_IDFK_1;
    public static final ForeignKey<QrcodeRecord, StudentRecord> QRCODE_IDFK_1 = ForeignKeys0.QRCODE_IDFK_1;
    public static final ForeignKey<StudentRecord, UserRecord> STUDENT_IDFK_1 = ForeignKeys0.STUDENT_IDFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CheckinsRecord, Integer> IDENTITY_CHECKINS = createIdentity(Checkins.CHECKINS, Checkins.CHECKINS.ID);
        public static Identity<QrcodeRecord, Integer> IDENTITY_QRCODE = createIdentity(Qrcode.QRCODE, Qrcode.QRCODE.ID);
        public static Identity<StudentRecord, Integer> IDENTITY_STUDENT = createIdentity(Student.STUDENT, Student.STUDENT.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CheckinsRecord> KEY_CHECKINS_PRIMARY = createUniqueKey(Checkins.CHECKINS, "KEY_checkins_PRIMARY", Checkins.CHECKINS.ID);
        public static final UniqueKey<QrcodeRecord> KEY_QRCODE_PRIMARY = createUniqueKey(Qrcode.QRCODE, "KEY_qrcode_PRIMARY", Qrcode.QRCODE.ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CheckinsRecord, StudentRecord> CHECKINS_IDFK_1 = createForeignKey(com.csc625.checkin.database.Keys.KEY_STUDENT_PRIMARY, Checkins.CHECKINS, "CheckIns_idfk_1", Checkins.CHECKINS.STUDENT_ID);
        public static final ForeignKey<QrcodeRecord, StudentRecord> QRCODE_IDFK_1 = createForeignKey(com.csc625.checkin.database.Keys.KEY_STUDENT_PRIMARY, Qrcode.QRCODE, "Qrcode_idfk_1", Qrcode.QRCODE.STUDENT_ID);
        public static final ForeignKey<StudentRecord, UserRecord> STUDENT_IDFK_1 = createForeignKey(com.csc625.checkin.database.Keys.KEY_USER_PRIMARY, Student.STUDENT, "student_idfk_1", Student.STUDENT.USER_ID);
    }
}
