/*
 * This file is generated by jOOQ.
*/
package com.csc625.checkin.database;


import com.csc625.checkin.database.tables.Checkins;
import com.csc625.checkin.database.tables.Qrcode;
import com.csc625.checkin.database.tables.Student;
import com.csc625.checkin.database.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in checkin
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>checkin.checkins</code>.
     */
    public static final Checkins CHECKINS = com.csc625.checkin.database.tables.Checkins.CHECKINS;

    /**
     * The table <code>checkin.qrcode</code>.
     */
    public static final Qrcode QRCODE = com.csc625.checkin.database.tables.Qrcode.QRCODE;

    /**
     * The table <code>checkin.student</code>.
     */
    public static final Student STUDENT = com.csc625.checkin.database.tables.Student.STUDENT;

    /**
     * The table <code>checkin.user</code>.
     */
    public static final User USER = com.csc625.checkin.database.tables.User.USER;
}
